# Generated by Django 4.0.5 on 2022-07-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("static_data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="active",
        ),
        migrations.RemoveField(
            model_name="city",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="city",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="college",
            name="active",
        ),
        migrations.RemoveField(
            model_name="college",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="college",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="country",
            name="active",
        ),
        migrations.RemoveField(
            model_name="country",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="country",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="pincode",
            name="active",
        ),
        migrations.RemoveField(
            model_name="pincode",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="pincode",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="state",
            name="active",
        ),
        migrations.RemoveField(
            model_name="state",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="state",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="university",
            name="active",
        ),
        migrations.RemoveField(
            model_name="university",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="university",
            name="updated_at",
        ),
    ]
