# Generated by Django 4.0.5 on 2022-07-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customusermodel",
            old_name="college_id",
            new_name="college",
        ),
    ]
