# Generated by Django 4.0.5 on 2022-09-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_stooferscard_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="college",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
